### PR TITLE
Add documentation for a simple component #79 issue solved

### PR DESCRIPTION
**Pull request by airwakz**

### CODE REVIEW

**Review by sansyrox — COMMENTED** [review]
Hey @airwakz :wave: 


Thank you for the PR and apologies for the late revert. Can you please move your contributions to a new file in the `docs/` section?

**Comment by sansyrox** [comment]
hey @airwakz :wave: 

Was the closing intentional??

**Comment by airwakz** [comment]
Yah I am new to github so I made the changes and closed the pr

**Comment by sansyrox** [comment]
@airwakz , you're not supposed to close the PR 😅 It will be automatically closed once a maintainer merges it.

**Comment by sansyrox** [comment]
Closing this PR as it is a bit outdated now.

**Pull request closed without merging**
